### ISSUE TITLE
where is s32k support?

### ISSUE THREAD

**Issue by gregory-essertel-ai** [xobs/openocd-s32k#1]
It seems like an old project, looking at the diff with openocd, I see that the rp2040 was added. But not really the s32k.

Do you have success using openocd for the s32k344?

thanks.

**Comment by xobs** [comment]
This was a temporary hack of a repository to add s32k1xx support. Specifically the 118 and 148. It worked well enough for the time, but since I don't have any personal need to work with any other parts I haven't looked.

The patch was also enough of a hack that it had no hope of making it upstream.

You might see if the flash controller is the same (it likely is). If so, you'd only have to find the memory parameters and integrate those into a target-specific driver.

Incidentally, the Blackmagic project supports S32K344, and it's different enough that it's in its own file: https://github.com/blackmagic-debug/blackmagic/blob/main/src/target/s32k3xx.c#L129-L140 so if you have supported hardware you might take a look there.

**Comment by gregory-essertel-ai** [comment]
thank you so much for the answer! I will look into blackmagic!
